###
POST http://localhost:8080/api/productos HTTP/1.1
Content-Type: application/json

{
    "title": "Los hijo de Hurin",
    "autor": "JRR Tolkien",
    "img": "lalala",
    "price": "3000",
    "stock": "5"
}

###
GET http://localhost:8080/api/productos HTTP/1.1

###
GET http://localhost:8080/api/productos/6304423ec5ce60c6af70826f HTTP/1.1

###
PUT http://localhost:8080/api/productos/630624c1f18503dc35a8e112 HTTP/1.1
Content-Type: application/json

{
    "title": "Los hijo de Hurin",
    "autor": "JRR Tolkien",
    "img": "lalala",
    "price": "3000",
    "stock": "5"
}

###
DELETE http://localhost:8080/api/productos/630623427d0547475bc5d397 HTTP/1.1

###
POST http://localhost:8080/api/carrito HTTP/1.1
Content-Type: application/json

{
   "productos": ""
}

###
GET http://localhost:8080/api/carrito/63069cbf261df7b7d3d3dba3/productos HTTP/1.1

###
DELETE  http://localhost:8080/api/carrito/6306aa06f5b60be159102572 HTTP/1.1

###
POST http://localhost:8080/api/carrito/63069ca2261df7b7d3d3dba0/productos HTTP/1.1
Content-Type: application/json

{
    "title": "El señor de los anillos",
    "autor": "JRR Tolkien",
    "img": "lalala",
    "price": "3000",
    "stock": "5"
}